### ISSUE TITLE
API downloadAnomalieAdresseAttachment - Supprimer le paramètre ifMatch

### ISSUE THREAD

**Issue by cbarbedette** [before-interop/anomalieAdresse#118]
L'API downloadAnomalieAdresseAttachment a un paramètre ifMatch obligatoire qui semble incohérent. Je suggère de le retirer.

**Comment by ericjacq92** [comment]
Je ne visualise pas le caractère "**obligatoire**" du paramètre If-Match pour l'opération downloadAnomalieAdresseAttachment. 

Il est défini en  [https://raw.githubusercontent.com/before-interop/common/v1/common/utils/update.openapi.yaml#/components/parameters/If-Match](https://raw.githubusercontent.com/before-interop/common/v1/common/utils/update.openapi.yaml#/components/parameters/If-Match) :
```
    If-Match:
      name: If-Match
      in: header
      schema:
        type: string
```
