### ISSUE TITLE
Définir un type explicite sur chaque attribut

### ISSUE THREAD

**Issue by ericjacq92** [before-interop/anomalieAdresse#75]
Postée par Bytel.
Cette issue est remontée par nos équipe technique en charge d'implémenter le swagger.
Ce problème déclenche des erreurs bloquantes dans les générateurs de code à partir du swagger Interop.

Le type n'est pas toujours explicite : il faut s'assurer que chaque attribut ait son type ==> il faut donc définir explicitement les types pour quelques objets.

Par exemple sur priority, ajouter `type: string`  :
```
        priority:
          readOnly: false
          enum:
            - LOW
            - MEDIUM
            - HIGH
          default: LOW
```
